# Generated by Django 4.2.4 on 2023-10-07 23:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default='', max_length=250, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('user_type_id', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.IntegerField(default=0)),
                ('cpf_cnpj', models.CharField(max_length=14, unique=True)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('andar', models.IntegerField(default=1)),
                ('lab', models.CharField(max_length=250)),
                ('is_active', models.IntegerField(default=0)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_date', models.DateTimeField(default=datetime.datetime.now)),
                ('lab_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.lab')),
                ('uer_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
