# Generated by Django 4.2.4 on 2023-09-28 20:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('andar', models.IntegerField(default=1)),
                ('lab', models.CharField(max_length=250)),
                ('is_active', models.IntegerField(default=0)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=250, unique=True)),
                ('email', models.CharField(max_length=250)),
                ('user_type_id', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.IntegerField(default=0)),
                ('cpf_cnpj', models.CharField(max_length=14, unique=True)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ResLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_date', models.DateTimeField(default=datetime.datetime.now)),
                ('id_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.lab')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.user')),
            ],
        ),
    ]
