# Generated by Django 4.2.4 on 2023-10-07 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reslab',
            old_name='uer_id',
            new_name='user_id',
        ),
    ]
