# Generated by Django 4.2.4 on 2023-10-09 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_rename_uer_id_reslab_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResLab',
            new_name='Res_Lab',
        ),
    ]
