# Generated by Django 4.2.4 on 2023-09-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_remove_reslab_res_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reslab',
            name='id_lab',
        ),
        migrations.RemoveField(
            model_name='reslab',
            name='id_user',
        ),
        migrations.AddField(
            model_name='reslab',
            name='nome',
            field=models.CharField(default='', max_length=250),
        ),
    ]
