# Generated by Django 4.2.4 on 2023-09-29 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_remove_reslab_id_lab_remove_reslab_id_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reslab',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
