# Generated by Django 4.2.4 on 2023-10-06 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_reslab_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reslab',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
