# Generated by Django 4.2.4 on 2023-10-06 23:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_alter_reslab_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reslab',
            name='nome',
        ),
        migrations.AddField(
            model_name='reslab',
            name='id_lab',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.lab'),
        ),
        migrations.AddField(
            model_name='reslab',
            name='res_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='reslab',
            name='id_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
